version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "release-machine"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-178onu6euafev"
s3_prefix = "release-machine"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

